'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

(async () => {
  assert.ok(process.env.IM_PREVIEW_URL, 'IM_PREVIEW_URL에 승인된 localhost 미리보기 주소를 지정해 주세요.');
  const executablePath = ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
  const browser = await chromium.launch({ headless: true, executablePath });
  try {
    const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
    const errors = [], requests = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(process.env.IM_PREVIEW_URL).origin) requests.push(request.url()); });
    await page.goto(new URL('prototype/login-preview/index.html', process.env.IM_PREVIEW_URL).href);
    const originalUrl = page.url();
    await page.locator('[data-account-demo="signup"]').click();
    await page.locator('#accountDemoContinue').click();
    assert.match(await page.locator('#accountDemoStatus').innerText(), /필수 항목/);
    await page.locator('#demoName').fill('시연 사용자');
    await page.locator('#demoEmail').fill('not-email');
    await page.locator('#demoId').fill('preview-owner');
    await page.locator('#demoPassword').fill('preview-password');
    await page.locator('#demoPasswordConfirm').fill('different-value');
    await page.locator('#accountDemoContinue').click();
    assert.match(await page.locator('#accountDemoStatus').innerText(), /이메일 형식/);
    await page.locator('#demoEmail').fill('owner@example.com');
    await page.locator('#accountDemoContinue').click();
    assert.match(await page.locator('#accountDemoStatus').innerText(), /두 비밀번호/);
    await page.locator('#demoPasswordConfirm').fill('preview-password');
    await page.locator('#accountDemoContinue').click();
    assert.match(await page.locator('#accountDemoResult').innerText(), /실제 계정은 만들어지지/);
    assert.equal(await page.locator('#accountDemoFields input').count(), 0);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#accountDemoDialog').isVisible(), false);
    assert.equal(await page.locator('[data-account-demo="signup"]').evaluate(el => el === document.activeElement), true);
    await page.locator('[data-account-demo="find-id"]').click();
    await page.locator('#demoName').fill('시연 사용자');
    await page.locator('#demoEmail').fill('owner@example.com');
    await page.locator('#accountDemoContinue').click();
    assert.match(await page.locator('#accountDemoResult').innerText(), /입력값과 연결된 조회 결과가 아닙니다/);
    await page.locator('#accountDemoClose').click();
    await page.locator('[data-account-demo="reset-password"]').click();
    await page.locator('#demoId').fill('preview-owner');
    await page.locator('#demoEmail').fill('owner@example.com');
    await page.locator('#demoPassword').fill('short');
    await page.locator('#demoPasswordConfirm').fill('short');
    await page.locator('#accountDemoContinue').click();
    assert.match(await page.locator('#accountDemoStatus').innerText(), /8자 이상/);
    await page.locator('#demoPassword').fill('preview-password');
    await page.locator('#demoPasswordConfirm').fill('preview-password');
    await page.locator('#demoPasswordConfirm').press('Enter');
    assert.match(await page.locator('#accountDemoResult').innerText(), /비밀번호 변경은 처리하지 않았으며/);
    assert.equal(page.url(), originalUrl);
    const output = path.resolve(__dirname, '../../tmp/login-preview-qa');
    fs.mkdirSync(output, { recursive: true });
    await page.screenshot({ path: path.join(output, 'account-demo-result.png') });
    await page.locator('#accountDemoClose').click();
    await page.setViewportSize({ width: 360, height: 800 });
    await page.locator('[data-account-demo="signup"]').click();
    const fit = await page.locator('#accountDemoDialog').evaluate(el => ({ overflow: el.scrollWidth - el.clientWidth, left: el.getBoundingClientRect().left, right: el.getBoundingClientRect().right }));
    assert.ok(fit.overflow <= 1 && fit.left >= 0 && fit.right <= 360);
    await page.screenshot({ path: path.join(output, 'account-demo-mobile.png') });
    await page.locator('#demoPassword').fill('erase-on-close');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#accountDemoFields input').count(), 0);
    assert.deepEqual(requests, []);
    assert.deepEqual(errors, []);
    console.log('PASS signup/id recovery/password reset demos: validation, explicit simulation, value clearing, focus return, responsive fit and no requests');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
