const assert = require('node:assert/strict');
const A = require('../aftercare.js');
const D = require('../meeting-data.js');
const record = {id:'test',date:'2026-09-03',startHour:19,endHour:21,actions:[{id:'menu',title:'메뉴 안내 점검',evidence:'생성 자료'}],note:'테스트 기록'};
const result = A.compare(D, record);
assert.equal(result.complete, true);
assert.equal(result.before.start, '2026-08-27');
assert.equal(result.before.end, '2026-09-02');
assert.equal(result.after.start, '2026-09-04');
assert.equal(result.after.end, '2026-09-10');
const manual = D.records.filter(r=>r.date>='2026-08-27'&&r.date<='2026-09-02'&&r.hour>=19&&r.hour<21).reduce((n,r)=>n+r.netAmount,0);
assert.equal(result.before.sales, manual);
const alteredDay = { ...D, records:[...D.records,{date:'2026-09-03',hour:20,netAmount:999999,netQuantity:1}] };
assert.equal(A.compare(alteredDay,record).delta,result.delta,'실행일은 비교에서 제외');
const removed = {...D, records:D.records.filter(r=>r.date!=='2026-09-04')};
assert.equal(A.compare(removed,record).complete,false,'누락은 0매출로 처리하지 않음');
assert.equal(A.compare(removed,record).rate,null);
const zero = {...removed, coverage:D.coverage.map(r=>r.date==='2026-09-04'?{...r,expectedRecords:0,expectedTransactions:0}:r)};
assert.equal(A.compare(zero,record).complete,true,'수집 완료된 정상 0매출일은 비교 포함');
const zeroAll = {...D, records:[],coverage:D.coverage.map(r=>({...r,expectedRecords:0,expectedTransactions:0}))};
assert.equal(A.compare(zeroAll,record).rate,null,'이전 매출0 분모 보호');
assert.equal(A.compare(zeroAll,record).delta,0);
assert.equal(A.compare(D,{...record,date:'2026-06-01'}).complete,false);
assert.equal(A.validate({...record,date:'2026-02-30'}),false);
assert.equal(A.validate({...record,endHour:18}),false);
assert.equal(A.validate({...record,actions:[]}),false);
const cache=new Map(), storage={getItem:k=>cache.get(k)||null,setItem:(k,v)=>cache.set(k,v)};
A.save(record,storage); assert.deepEqual(A.read(storage),[record]);
assert.throws(()=>A.save(record,{getItem:()=>null,setItem:()=>{throw Error('denied');}}),/저장/);
cache.set(A.KEY,'bad json'); assert.deepEqual(A.read(storage),[]);
cache.set(A.KEY,JSON.stringify([{...record,date:'invalid'},record])); assert.equal(A.read(storage).length,1);
console.log('aftercare: before/after periods, hour scope, zero/missing distinction, validation and storage passed');
