'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const data = require('../market-analysis-data.js');
const context = { window: { IM_MARKET_DATA: data } };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../market-analysis.js'), 'utf8'), context);
const ui = context.window.IM_MARKET_ANALYSIS;
const period = { start: '2026-08-01', end: '2026-08-31' };
const result = data.analyze(period, { camera: 'front', days: [], comparison: 'weekday' });
const html = ui.render(period);
assert.equal((html.match(/class="ma-panel"/g) || []).length, 4);
assert.equal((html.match(/data-ma-detail="slot"/g) || []).length, 36);
assert.equal((html.match(/data-ma-day="/g) || []).length, 7);
assert.ok(!/ma-observation|ma-camera"|ma-comparison"|data-ma-chart="dwell"|2시간|08~20|NaN|Infinity|undefined/.test(html));
assert.match(html, /10분당 통행 관측/);
assert.match(html, /매장 전면/);
assert.ok(result.current.averagePerTenMinutes > 0);
assert.ok(Math.abs(result.observedHours - result.current.count / 6) < 1e-9);
assert.ok(html.includes(result.current.averagePerTenMinutes.toLocaleString('ko-KR', { maximumFractionDigits: 1 })));
assert.ok(html.includes('17:00~17:10'));
assert.ok(html.includes('22:50~23:00'));
let providedResult;
ui.setExtrasRenderer(value => { providedResult = value; return '<p>홈에서 이동한 영역</p>'; });
assert.match(ui.render(period), /ma-relocated-extras"><p>홈에서 이동한 영역/);
assert.equal(providedResult.current.count, result.current.count);
ui.setExtrasRenderer(null);
assert.ok(!ui.render(period).includes('ma-relocated-extras'));
console.log('PASS market meeting UI: four panels, 36 ten-minute rows, correct units, removed controls and extras integration');
