'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
const D = require('../market-analysis-data.js');
(async () => {
  const executablePath = ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
  const browser = await chromium.launch({ headless: true, executablePath });
  try {
    const output = path.resolve(__dirname, '../../tmp/market-analysis-qa'); fs.mkdirSync(output, { recursive: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: process.env.IM_TEST_MOTION === 'normal' ? 'no-preference' : 'reduce' });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    const url = pathToFileURL(path.resolve(__dirname, '../main-screen.html')).href;
    await page.goto(url + '#recovery');
    await page.evaluate(() => document.fonts.ready);
    assert.ok(page.url().endsWith('#market'), 'old recovery links migrate to market analysis');
    assert.equal(await page.locator('#viewRoot > .v-screen-section').count(), 5);
    assert.equal(await page.getByRole('button', { name: '상권분석', exact: true }).count(), 1);
    assert.equal(await page.getByRole('button', { name: '회복전략', exact: true }).count(), 0);
    assert.equal(await page.locator('.ma-metric').count(), 4);
    const month = D.analyze({ start: '2026-08-01', end: '2026-08-31' });
    assert.match(await page.locator('.ma-quality-strip').innerText(), new RegExp(month.current.passers.toLocaleString('ko-KR')));
    assert.ok(!(await page.locator('#viewRoot').innerText()).includes('실행 기록 시안 시작하기'));
    await page.screenshot({ path: path.join(output, 'market-overview-desktop.png') });
    await page.locator('[data-ma-jump="1"]').first().click();
    await page.selectOption('#ma-date', '2026-08-27'); await page.selectOption('#ma-slot', '12');
    const observed = D.rows.find(row => row.cameraId === 'front' && row.date === '2026-08-27' && row.slotId === '12');
    assert.match(await page.locator('.ma-observed-values').innerText(), new RegExp(String(observed.passers)));
    await page.locator('[data-ma-layer="dwell"]').click();
    assert.equal(await page.locator('[data-ma-layer="dwell"]').getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('.ma-scene svg').getAttribute('aria-label'), /머무는/);
    await page.locator('[data-ma-layer="entry"]').click();
    assert.match(await page.locator('.ma-scene svg').getAttribute('aria-label'), /출입선/);
    await page.locator('[data-ma-detail="observation"]').click();
    assert.equal(await page.locator('#ma-dialog').isVisible(), true);
    assert.equal(await page.locator('#ma-dialog tbody tr').count(), 1);
    assert.match(await page.locator('#ma-dialog').innerText(), /2026-08-27/);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#ma-dialog').isVisible(), false);
    await page.locator('[data-ma-jump="0"]').first().click(); await page.locator('[data-ma-jump="2"]').click();
    await page.locator('[data-ma-chart="entry"]').click();
    const entrySlot = month.bySlot[0];
    assert.match(await page.locator('[data-ma-detail="slot"]').first().innerText(), new RegExp(entrySlot.entryRate.toFixed(1).replace('.', '\\.')));
    await page.locator('[data-ma-detail="slot"]').first().click();
    assert.equal(await page.locator('#ma-dialog tbody tr').count(), 8);
    await page.locator('[data-ma-page="1"]').click();
    assert.match(await page.locator('.ma-pagination').innerText(), /2\/4/);
    await page.screenshot({ path: path.join(output, 'market-detail-desktop.png') });
    await page.locator('[data-ma-close]').click();
    await page.locator('[data-ma-jump="0"]').first().click(); await page.locator('[data-ma-jump="4"]').first().click();
    await page.locator('[data-ma-evidence="18"]').first().click();
    assert.equal(await page.locator('#ma-slot').inputValue(), '18');
    assert.equal(await page.locator('#ma-observation').evaluate(el => el.closest('section').getBoundingClientRect().top < 150), true);
    await page.locator('[data-ma-jump="0"]').first().click();
    await page.selectOption('#ma-camera', 'alley');
    assert.match(await page.locator('.ma-quality-strip').innerText(), /184 \/ 186구간/);
    assert.match(await page.locator('.ma-metrics').innerText(), /관측 범위 밖/);
    assert.equal(await page.locator('[data-ma-chart="entry"]').isDisabled(), true);
    assert.equal(await page.locator('[data-ma-layer="entry"]').isDisabled(), true);
    assert.equal(await page.locator('[data-ma-chart="traffic"]').getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('.ma-notice').first().innerText(), /누락/);
    await page.locator('[data-ma-jump="1"]').first().click();
    await page.selectOption('#ma-date', '2026-08-26'); await page.selectOption('#ma-slot', '18');
    assert.match(await page.locator('#ma-observation').innerText(), /분석 자료가 없습니다/);
    await page.selectOption('#ma-date', '2026-08-31'); await page.selectOption('#ma-slot', '16');
    assert.match(await page.locator('#ma-observation').innerText(), /가림이 있어/);
    await page.locator('[data-ma-jump="0"]').first().click();
    await page.selectOption('#ma-camera', 'gate');
    assert.match(await page.locator('.ma-lead').innerText(), /연결되지 않았습니다/);
    assert.equal(await page.locator('[data-ma-evidence]').count(), 0);
    assert.ok(!/NaN|Infinity|undefined/.test(await page.locator('#viewRoot').innerText()));
    await page.screenshot({ path: path.join(output, 'market-unconnected.png') });
    await page.locator('[data-ma-reset]').click();
    await page.selectOption('#ma-comparison', 'weekday');
    assert.match(await page.locator('.ma-period').innerText(), /2026-06-27/);
    assert.match(await page.locator('.ma-notice').innerText(), /이전 기간/);
    await page.selectOption('#sectionPeriodSelect', 'week');
    assert.match(await page.locator('.ma-period').innerText(), /2026-08-20 ~ 2026-08-26/);
    await page.selectOption('#sectionPeriodSelect', 'custom');
    await page.fill('#sectionPeriodStart', '2026-08-30'); await page.fill('#sectionPeriodEnd', '2026-08-30');
    await page.locator('#sectionCustomPeriod button').click(); await page.selectOption('#ma-dayType', 'weekday');
    assert.match(await page.locator('.ma-lead').innerText(), /해당하는 날짜가 없습니다/);
    assert.ok(!/NaN|Infinity|undefined/.test(await page.locator('#viewRoot').innerText()));
    await page.locator('[data-ma-reset]').click(); await page.selectOption('#sectionPeriodSelect', 'month');
    await page.getByRole('button', { name: 'iM비서', exact: true }).click();
    assert.equal(await page.locator('[data-report-question]').count(), 3);
    await page.locator('[data-report-question]').first().click();
    await page.getByRole('button', { name: '회복전략 리포트 PDF 만들기', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#pdfLink')?.getAttribute('href')?.startsWith('blob:'));
    assert.equal(await page.locator('#pdfLink').getAttribute('download'), 'iM파트너_회복전략_리포트.pdf');
    const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#pdfLink').click()]);
    assert.equal(fs.readFileSync(await download.path()).subarray(0, 8).toString(), '%PDF-1.4');
    for (const [width, height] of [[1920, 1080], [1366, 768], [768, 1024], [390, 844], [360, 800]]) {
      await page.setViewportSize({ width, height }); await page.goto(url + '?market-qa=' + width + '#market'); await page.evaluate(() => document.fonts.ready);
      assert.equal(await page.locator('#viewRoot > .v-screen-section').count(), 5);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1), 'horizontal page overflow at ' + width);
      for (let i = 0; i < 5; i++) {
        const section = page.locator('#viewRoot > .v-screen-section').nth(i);
        await section.evaluate(el => el.scrollIntoView({ behavior: 'instant' }));
        const fit = await section.evaluate(el => { const inner = el.querySelector('.v-screen-inner'); return { x: inner.scrollWidth - inner.clientWidth, y: inner.scrollHeight - inner.clientHeight, overflow: getComputedStyle(inner).overflowY }; });
        assert.ok(fit.x <= 2, width + ' section ' + i + ' horizontal overflow: ' + fit.x);
        assert.ok(fit.y <= 2 || ['auto', 'scroll'].includes(fit.overflow), width + ' section ' + i + ' inaccessible content');
        if (width === 1366 || width === 390) await page.screenshot({ path: path.join(output, 'market-section-' + (i + 1) + '-' + width + '.png') });
      }
    }
    assert.deepEqual(errors, []);
    console.log('PASS market browser: 5 sections, route migration, camera/period filters, observation diagram, metric toggles, drilldown, evidence jumps, missing/occluded/unconnected/empty states, renamed PDF and 5 responsive widths');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
