'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
(async () => {
  const executablePath = ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
  const browser = await chromium.launch({ headless: true, executablePath });
  try {
    const output = path.resolve(__dirname, '../../tmp/market-analysis-qa'); fs.mkdirSync(output, { recursive: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    await page.clock.setFixedTime(new Date('2026-09-18T10:16:00Z'));
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    const url = process.env.IM_PREVIEW_URL ? new URL('prototype/main-screen.html', process.env.IM_PREVIEW_URL).href : pathToFileURL(path.resolve(__dirname, '../main-screen.html')).href;
    await page.goto(url + '#market');
    await page.evaluate(() => document.fonts.ready);
    assert.equal(await page.locator('.ma-panel').count(), 4);
    assert.deepEqual(await page.locator('.ma-heading h2').allTextContents(), ['상권 요약', '시간대·요일별 진단', '방문·결제 진단', '주변상권 진단']);
    assert.equal(await page.locator('.ma-kicker, #ma-timeWindow, .ma-time-filter, .ma-insight-index, #ma-insights').count(), 0);
    assert.equal(await page.locator('.ma-fixed-camera strong').innerText(), '매장 앞 CCTV');
    assert.deepEqual(await page.locator('[data-ma-day]').allTextContents(), ['전체', '월', '화', '수', '목', '금', '토', '일']);
    assert.equal(await page.locator('#ma-multiple-days').isChecked(), false);
    assert.equal(await page.locator('.ma-live-metrics > article').count(), 4);
    assert.equal(await page.locator('.ma-weekday-mini-row').count(), 0);
    assert.equal(await page.locator('.ma-live-metrics .metric-value').count(), 4);
    assert.equal(await page.locator('.ma-live-metrics svg, .ma-live-metrics .ma-bar-pair').count(), 0);
    const expected = await page.evaluate(() => IM_MARKET_DATA.getLiveSnapshot(new Date()));
    assert.match(await page.locator('.ma-live-lead').innerText(), /\(19:16\)/);
    assert.match(await page.locator('.ma-observation-time').innerText(), /2026-09-18 19:00~19:10/);
    assert.ok((await page.locator('.ma-live-lead').innerText()).includes(expected.traffic.text));
    assert.match(await page.locator('[data-ma-live-metric="passers"]').innerText(), new RegExp(expected.current.passers.toLocaleString('ko-KR') + '건'));
    assert.match(await page.locator('.ma-trend-charts .ma-scope').first().innerText(), /기간: 2026-08-01~2026-08-31/);
    assert.ok(!/체류|월간 상권 분석 요약/.test(await page.locator('#viewRoot').innerText()));
    const liveBeforeFilter = await page.locator('.ma-live-lead').innerText();
    await page.locator('#ma-day-1').click();
    await page.locator('#ma-day-3').click();
    assert.equal(await page.locator('#ma-day-1').getAttribute('aria-pressed'), 'false');
    assert.equal(await page.locator('#ma-day-3').getAttribute('aria-pressed'), 'true');
    await page.locator('#ma-multiple-days').check();
    await page.locator('#ma-day-1').click();
    assert.equal(await page.locator('#ma-day-1').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('#ma-day-3').getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('.ma-trend-charts .ma-scope').first().innerText(), /월·수/);
    assert.equal(await page.locator('.ma-live-lead').innerText(), liveBeforeFilter, 'weekday filters must not change the current ten-minute observation');
    const recoveryContext = await page.evaluate(() => IM_MARKET_ANALYSIS.getRecoveryContext());
    assert.match(recoveryContext.scope, /2026-08-01~2026-08-31.*월·수/);
    const selectedFindings = await page.evaluate(() => IM_MARKET_DATA.recoveryContext(IM_MARKET_DATA.monthlySummary(new Date(), { days: [1, 3] })).findings);
    assert.deepEqual(recoveryContext.findings, selectedFindings);
    await page.evaluate(() => { location.hash = '#recovery'; });
    await page.locator('#reportInput').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-recovery-source]').count(), 0, 'recovery uses the single conversation workspace');
    assert.deepEqual(await page.evaluate(() => IM_MARKET_ANALYSIS.getRecoveryContext()), recoveryContext, 'market context is retained when opening recovery');
    await page.locator('#mainNavigation [data-view="market"]').click();
    assert.equal(await page.locator('#ma-day-1').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('#ma-day-3').getAttribute('aria-pressed'), 'true');
    await page.locator('#ma-multiple-days').uncheck();
    assert.equal(await page.locator('#ma-day-1').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('#ma-day-3').getAttribute('aria-pressed'), 'false');
    await page.locator('[data-ma-reset]').click();
    await page.locator('[data-ma-detail="live"]').click();
    await page.locator('#ma-dialog').waitFor({ state: 'visible' });
    assert.match(await page.locator('#ma-dialog-title').innerText(), /\(19:00\)/);
    assert.equal(await page.locator('#ma-dialog tbody tr').count(), 1);
    assert.doesNotMatch(await page.locator('#ma-dialog').innerText(), /체류/);
    assert.match(await page.locator('#ma-dialog .ma-scope').innerText(), /기간: 2026-09-18~2026-09-18.*19:00~19:10/);
    await page.keyboard.press('Escape');
    await page.locator('.ma-live-lead [data-ma-jump="3"]').click();
    assert.equal(await page.locator('#ma-trends').count(), 1);
    await page.locator('[data-ma-detail="hour"]').first().click();
    await page.locator('#ma-dialog').waitFor({ state: 'visible' });
    assert.match(await page.locator('#ma-dialog-title').innerText(), /17~18시/);
    assert.equal(await page.locator('#ma-dialog tbody tr').count(), 8);
    await page.locator('[data-ma-page="1"]').click();
    assert.match(await page.locator('.ma-pagination').innerText(), /2\//);
    await page.keyboard.press('Escape');
    await page.locator('[data-ma-chart="entry"]').click();
    assert.match(await page.locator('#ma-movements').innerText(), /시간대별 입장률/);
    assert.equal(await page.locator('[data-ma-detail="hour"]').count(), 6);
    assert.equal(await page.locator('[data-ma-detail="weekday"]').count(), 7);
    await page.evaluate(() => { window.__marketSurroundings = document.getElementById('ma-trends'); });
    await page.clock.setFixedTime(new Date('2026-09-18T10:17:00Z'));
    await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
    assert.equal(await page.locator('[data-ma-clock]').innerText(), '19:17', 'current time changes within the same observation bucket');
    assert.match(await page.locator('.ma-observation-time').innerText(), /19:00~19:10/);
    assert.ok(await page.evaluate(() => window.__marketSurroundings === document.getElementById('ma-trends')), 'minute refresh preserves surroundings/map DOM');
    await page.clock.setFixedTime(new Date('2026-09-18T10:26:00Z'));
    await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
    assert.equal(await page.locator('[data-ma-clock]').innerText(), '19:26');
    assert.match(await page.locator('.ma-observation-time').innerText(), /19:10~19:20/, 'returning to the tab refreshes a completed ten-minute bucket without navigation');
    assert.ok(await page.evaluate(() => window.__marketSurroundings === document.getElementById('ma-trends')), 'ten-minute refresh preserves surroundings/map DOM');
    assert.match(await page.locator('.ma-trend-charts .ma-scope').first().innerText(), /기간: 2026-08-01~2026-08-31/);
    await page.clock.setFixedTime(new Date('2026-09-19T00:01:00Z'));
    await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
    assert.equal(await page.locator('[data-ma-clock]').innerText(), '09:01');
    assert.match(await page.locator('.ma-observation-time').innerText(), /2026-09-18 22:50~23:00 · 마지막 완료 관측/);
    assert.match(await page.locator('.ma-live-lead').innerText(), /운영시간 밖/);
    for (const [width, height] of [[1440, 900], [1366, 768], [768, 1024], [390, 844], [360, 800]]) {
      await page.setViewportSize({ width, height }); await page.goto(url + '?market-qa=' + width + '#market');
      await page.evaluate(() => document.fonts.ready);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1), 'horizontal overflow at ' + width);
      const panels = page.locator('.ma-panel');
      for (let i = 0; i < 4; i++) {
        await panels.nth(i).evaluate(el => el.closest('.v-screen-section').scrollIntoView({ behavior: 'instant', block: 'start' }));
        const overflow = await panels.nth(i).evaluate(el => el.scrollWidth - el.clientWidth);
        assert.ok(overflow <= 2, width + ' panel ' + i + ' content overflow: ' + overflow);
        if (i <= 2) await page.screenshot({ path: path.join(output, 'market-panel-' + i + '-' + width + '.png') });
      }
      assert.ok(!/NaN|Infinity|undefined/.test(await page.locator('#viewRoot').innerText()));
    }
    assert.deepEqual(errors, []);
    console.log('PASS market UI: live minute clock without map reload, dated off-hours, numeric cards, compact hourly/weekday comparisons, recovery, drilldowns and five responsive sizes');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
