'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const data = require('../market-analysis-data.js');
const now = new Date('2026-09-18T10:16:00Z');
const context = { window: { IM_MARKET_DATA: { ...data, monthlySummary: (_, filters) => data.monthlySummary(now, filters), getLiveSnapshot: () => data.getLiveSnapshot(now) } } };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../market-analysis.js'), 'utf8'), context);
const ui = context.window.IM_MARKET_ANALYSIS;
const monthly = data.monthlySummary(now, { camera: 'front', days: [], comparison: 'weekday', timeWindow: 'all' });
const live = data.getLiveSnapshot(now);
let html = ui.render();
assert.equal((html.match(/class="ma-panel"/g) || []).length, 4);
assert.equal((html.match(/data-ma-day="/g) || []).length, 8);
assert.match(html, /id="ma-multiple-days" data-ma-multiple>/);
assert.ok(!/ma-kicker|ma-timeWindow|ma-insight-index|체류|ma-weekday-mini|NaN|Infinity|undefined/.test(html));
assert.match(html, /상권 요약/);
assert.match(html, /주변상권 진단/);
assert.match(html, /방문·결제 진단/);
assert.match(html, /시간대·요일별 진단/);
assert.ok(!/월간 상권 분석 요약|ma-insights/.test(html));
assert.match(html, /매장 앞 CCTV/);
assert.match(html, /최근 10분 통행 관측/);
assert.match(html, /같은 요일 통행 평균/);
assert.match(html, /최근 10분 입장률/);
assert.match(html, /같은 요일 입장률 평균/);
assert.match(html, /현재 시각 1분마다 갱신/);
assert.match(html, /data-ma-clock[^>]*>19:16<\/time>/);
assert.match(html, /관측 기준 · 2026-09-18 19:00~19:10/);
assert.equal((html.match(/data-ma-live-metric="/g) || []).length, 4);
assert.equal((html.match(/data-ma-detail="hour"/g) || []).length, 6);
assert.equal((html.match(/data-ma-detail="weekday"/g) || []).length, 7);
assert.match(html, /class="ma-change is-(up|down)"/);
assert.ok(html.includes(live.traffic.text));
assert.ok(html.includes(live.slot.intervalLabel));
assert.match(html, /기간: 2026-08-01~2026-08-31/);
assert.ok(!html.includes('2026-09-01 ~ 2026-09-18'));
assert.deepEqual(ui.getRecoveryContext(), data.recoveryContext(monthly));
assert.match(html, /data-ma-jump="3"[^>]*>주변상권 진단 보기/);
assert.deepEqual(Array.from(html.matchAll(/class="ma-panel" id="([^"]+)"/g), match => match[1]), ['ma-overview', 'ma-movements', 'ma-behavior', 'ma-trends']);
const renderedSections = [];
ui.setExtrasRenderer((value, section) => { renderedSections.push({ period: value.period, section }); return '<p>' + section + '-content</p>'; });
html = ui.render();
assert.match(html, /surroundings-content/);
assert.match(html, /conversion-content/);
assert.deepEqual(renderedSections.map(item => item.section), ['conversion', 'surroundings']);
assert.ok(renderedSections.every(item => item.period.start === '2026-08-01' && item.period.end === '2026-08-31'));
const contextFindings = ui.getRecoveryContext().findings;
assert.ok(contextFindings.every(item => !item.action || !html.includes(item.action)), 'operational recommendations stay in recovery');
context.window.IM_MARKET_DATA.getLiveSnapshot = () => data.getLiveSnapshot(new Date('2026-09-18T00:01:00Z'));
html = ui.render();
assert.match(html, /data-ma-clock[^>]*>09:01<\/time>/);
assert.match(html, /관측 기준 · 2026-09-17 22:50~23:00 · 마지막 완료 관측/);
assert.match(html, /마지막 10분 통행 관측/);
assert.match(html, /지금은 관측 운영시간 밖입니다/);
assert.deepEqual(ui.getRecoveryContext(), data.recoveryContext(monthly), 'removing monthly summary UI retains recovery evidence');
console.log('PASS market UI: numeric comparison cards, current clock versus dated observations, hourly/weekday comparisons, removed monthly summary and retained recovery');
