'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const {chromium}=require('playwright');
const url=process.env.IM_PREVIEW_URL?new URL('prototype/main-screen.html',process.env.IM_PREVIEW_URL).href:pathToFileURL(path.resolve(__dirname,'../main-screen.html')).href;
const out=process.env.IM_QA_DIR||path.resolve(__dirname,'../../tmp/meeting-structure-qa');
(async()=>{
 fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install({time:new Date('2026-09-18T19:16:00+09:00')});
  await page.goto(url);await page.evaluate(()=>document.fonts.ready);
  assert.deepEqual(await page.locator('#mainNavigation .nav-label').allTextContents(),['홈','매출진단','상권분석','지원사업','회복전략']);
  assert.equal(await page.locator('.demo-label').count(),0);
  assert.equal(await page.locator('#financeThermoTitle').innerText(),'나의 가게 온도');
  await page.locator('#profileMenuButton').click();
  assert.equal(await page.locator('.ipf-profile-finance__heading strong').innerText(),'나의 가게 온도');
  assert.equal(await page.locator('.ipf-profile-finance__basis').count(),0);
  await page.screenshot({path:path.join(out,'profile.png')});
  await page.locator('.ipf-profile-finance__button').click();
  assert.equal(new URL(page.url()).hash,'#dashboard');
  assert.equal(await page.locator('#aiToggle').getAttribute('aria-label'),'iM비서');
  await page.locator('#mainNavigation [data-view="policies"]').click();
  assert.equal(await page.locator('#viewRoot .v-plan-list').count(),0,'guide hidden by default');
  await page.locator('[data-action="open-policy-guide"]').click();
  assert.ok(await page.locator('#policyModal').evaluate(n=>n.open));
  assert.match(await page.locator('#policyModal').innerText(),/지원사업 확인 순서/);
  await page.screenshot({path:path.join(out,'policy-guide.png')});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#policyModal').evaluate(n=>n.open),false);
  await page.locator('[data-action="open-policy-guide"]').click();
  await page.locator('#policyModal [data-view="profile"]').click();
  assert.equal(await page.locator('#policyModal').evaluate(n=>n.open),false);
  assert.equal(new URL(page.url()).hash,'#profile');
  await page.locator('#mainNavigation [data-view="analysis"]').click();
  assert.deepEqual(await page.locator('.sd-section-heading h2').allTextContents(),['매출 요약','일별 매출 진단','요일별 진단','품목별 진단','지출 진단']);
  assert.equal(await page.locator('#sd-panel-daily-weekly .sd-section-heading').count(),2);
  assert.match(await page.locator('.sd-period-line').innerText(),/2026-08-01 ~ 2026-08-31/);
  assert.equal(await page.locator('.sd-kicker,.sd-heatmap,.sd-effects').count(),0);
  assert.match(await page.locator('.sd-metrics').innerText(),/순이익/);
  await page.locator('#mainNavigation [data-view="market"]').click();
  assert.deepEqual(await page.locator('.ma-heading h2').allTextContents(),['상권 요약','시간대·요일별 진단','방문·결제 진단','주변상권 진단']);
  assert.match(await page.locator('.ma-live-lead').innerText(),/\(19:16\)/);
  assert.match(await page.locator('.ma-observation-time').innerText(),/19:00~19:10/);
  assert.equal(await page.locator('[data-ma-live-metric]').count(),4);
  assert.equal(await page.locator('#viewRoot select,.ma-kicker,.v-context-action,.v-comparison-chart,.ma-flow-branches').count(),0);
  assert.ok(!(await page.locator('#viewRoot').innerText()).includes('체류'));
  assert.equal(await page.locator('[data-neighborhood-hour]').count(),6);
  assert.equal(await page.locator('[data-neighborhood-hour="0"]').count(),0);
  assert.equal(await page.locator('.ma-live-metrics svg,.ma-weekday-mini').count(),0);
  assert.equal(await page.locator('#ma-trends [data-nearby-events]').count(),1);
  assert.match(await page.locator('[data-ne-map]').getAttribute('src'),/^https:\/\/www.openstreetmap.org\/export\/embed.html/);
  const traffic=await page.locator('[data-neighborhood-hour="19"] strong').innerText();
  await page.locator('[data-context-mode="consumption"]').click();
  assert.notEqual(await page.locator('[data-neighborhood-hour="19"] strong').innerText(),traffic);
  assert.match(await page.locator('#ma-movements .ma-scope').innerText(),/2026-08-01 ~ 2026-08-31/);
  assert.equal(await page.locator('#ma-insights').count(),0);
  await page.locator('[data-ma-day="1"]').click();
  assert.match(await page.locator('#ma-movements .ma-scope').innerText(),/월/);
  const slotBefore=await page.locator('.ma-observation-time').innerText();
  await page.evaluate(()=>window._preservedMap=document.querySelector('[data-ne-map]'));
  await page.clock.setSystemTime(new Date('2026-09-18T19:19:00+09:00'));
  await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
  assert.equal(await page.locator('.ma-observation-time').innerText(),slotBefore);
  assert.match(await page.locator('.ma-live-lead .v-tag').innerText(),/\(19:19\)/);
  await page.clock.setSystemTime(new Date('2026-09-18T19:20:00+09:00'));
  await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
  assert.match(await page.locator('.ma-live-lead .v-tag').innerText(),/\(19:20\)/);
  assert.match(await page.locator('.ma-observation-time').innerText(),/19:10~19:20/);
  assert.ok(await page.evaluate(()=>window._preservedMap===document.querySelector('[data-ne-map]')),'ten-minute refresh preserves map');
  await page.clock.setSystemTime(new Date('2026-09-19T09:01:00+09:00'));
  await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
  assert.match(await page.locator('.ma-live-lead .v-tag').innerText(),/\(09:01\)/);
  assert.match(await page.locator('.ma-observation-time').innerText(),/2026-09-18.*22:50~23:00.*마지막 완료/);
  await page.clock.fastForward(60000);
  assert.equal(await page.locator('[data-ma-clock]').innerText(),'09:02');
  assert.deepEqual(errors,[]);
  console.log('PASS meeting revision: combined sales diagnoses, numeric cards, current clock/observation separation, compact surroundings and map, restored comparisons, minute/ten-minute/midnight updates');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
