'use strict';
// The event map is now the nearby-industry preview. Events remain a plain list.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const data = require('../data/daegu-festivals.json');
const base = process.env.IM_PREVIEW_URL || 'http://127.0.0.1:8897/';
const output = path.resolve(__dirname, '../../tmp/screen-revision-qa');
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const executablePath = ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
  const browser = await chromium.launch({ headless: true, executablePath });
  const errors = [], externalRequests = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', timezoneId: 'Asia/Seoul' });
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (new URL(request.url()).hostname !== '127.0.0.1') externalRequests.push(request.url()); });
    await page.clock.setFixedTime(new Date('2026-09-20T10:16:00Z'));
    await page.goto(new URL('prototype/login-preview/index.html', base).href);
    assert.deepEqual(await page.locator('.feature-list strong').allTextContents(), ['매출진단', '상권분석', '지원사업', '회복전략']);
    await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: path.join(output, 'guest-desktop.png'), fullPage: true });
    await page.getByRole('link', { name: '데모시작' }).click();
    assert.equal(await page.locator('#profileMenuStore').innerText(), '달구벌 고기마당');
    assert.equal(await page.locator('.v-finance-thermo-notice').innerText(), '참고용 지표로, 신용평가·대출심사 결과와는 무관합니다.');
    await page.screenshot({ path: path.join(output, 'home-desktop.png') });
    await page.getByRole('button', { name: '상권분석', exact: true }).click();
    await page.locator('.nb-event-list li').first().waitFor();
    await page.locator('[data-nearby-businesses]').scrollIntoViewIfNeeded();
    const center = await page.locator('.nb-store').evaluate(node => ({ left: node.style.left, top: node.style.top }));
    assert.equal(await page.locator('[data-ne-period]').count(), 0);
    assert.equal(await page.locator('[data-nb-radius]').inputValue(), '5');
    assert.equal(await page.locator('[data-nb-pin]').count(), 8);
    assert.equal(await page.locator('.nb-event-list li').count(), data.events.length);
    const names = await page.locator('.nb-event-list strong').allTextContents();
    assert.deepEqual(names.slice().sort(), data.events.map(row => row.name).sort());
    await page.locator('[data-nb-pin]').last().click();
    assert.match(await page.locator('[data-nb-selection]').innerText(), /가상 고깃집 H.*4.8km/);
    assert.deepEqual(await page.locator('.nb-store').evaluate(node => ({ left: node.style.left, top: node.style.top })), center, 'selecting a peer never moves the store');
    for (const [radius, count] of [['0.5', 1], ['1', 2], ['3', 5], ['5', 8]]) {
      await page.locator('[data-nb-radius]').selectOption(radius);
      assert.equal(await page.locator('[data-nb-pin]').count(), count);
      assert.equal(await page.locator('[data-nb-count]').innerText(), '동종업소 ' + count + '곳');
      assert.equal(Number(await page.locator('[data-nb-circle]').getAttribute('r')), Number(radius) * 27);
      assert.equal(await page.locator('[data-nb-circle]').getAttribute('cx'), '260');
      assert.equal(await page.locator('[data-nb-circle]').getAttribute('cy'), '175');
      assert.deepEqual(await page.locator('.nb-event-list strong').allTextContents(), names, 'radius never changes the festival list');
    }
    await page.locator('[data-nb-pin]').first().focus();
    await page.keyboard.press('Enter');
    assert.match(await page.locator('[data-nb-selection]').innerText(), /가상 고깃집 A/);
    await page.evaluate(() => { window.__originalNearbyMap = document.querySelector('[data-nb-map]'); });
    await page.clock.setFixedTime(new Date('2026-09-20T10:26:00Z'));
    await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
    assert.ok(await page.evaluate(() => window.__originalNearbyMap === document.querySelector('[data-nb-map]')), 'clock updates preserve the map');
    for (const [width, height] of [[1440, 1000], [1366, 768], [768, 1024], [390, 844], [360, 800]]) {
      await page.setViewportSize({ width, height });
      await page.locator('[data-nearby-businesses]').scrollIntoViewIfNeeded();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'no page overflow at ' + width);
      assert.ok(await page.locator('[data-nearby-businesses]').evaluate(card => card.scrollWidth <= card.clientWidth + 1), 'no map card overflow at ' + width);
      const mapSize = await page.locator('.nb-map').boundingBox();
      assert.ok(Math.abs(mapSize.width / mapSize.height - 520 / 350) < .02, 'round radius stays round at ' + width);
      await page.locator('[data-nearby-businesses]').screenshot({ path: path.join(output, 'neighborhood-card-' + width + '.png') });
      if (width === 1440 || width === 390) await page.screenshot({ path: path.join(output, 'neighborhood-' + width + '.png') });
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('[data-nb-radius]').selectOption('3');
    await page.getByRole('button', { name: '홈', exact: true }).click();
    await page.getByRole('button', { name: '상권분석', exact: true }).click();
    assert.equal(await page.locator('[data-nb-radius]').inputValue(), '3', 'view changes preserve the distance selection');
    await page.goto(new URL('prototype/login-preview/index.html', base).href);
    await page.setViewportSize({ width: 360, height: 800 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.screenshot({ path: path.join(output, 'guest-mobile.png'), fullPage: true });
    const offline = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    offline.on('pageerror', error => errors.push(error.message));
    await offline.route('**/data/daegu-festivals.json', route => route.fulfill({ status: 500, body: '' }));
    await offline.goto(new URL('prototype/main-screen.html#market', base).href);
    await offline.getByRole('button', { name: '다시 불러오기', exact: true }).waitFor();
    assert.equal(await offline.locator('[data-nb-pin]').count(), 8, 'missing event file never disables the map');
    await offline.locator('[data-nb-radius]').selectOption('1');
    assert.equal(await offline.locator('[data-nb-pin]').count(), 2);
    await offline.unroute('**/data/daegu-festivals.json');
    await offline.getByRole('button', { name: '다시 불러오기', exact: true }).click();
    await offline.locator('.nb-event-list li').first().waitFor();
    assert.equal(await offline.locator('.nb-event-list li').count(), data.events.length);
    assert.equal(await offline.locator('[data-nb-pin]').count(), 2, 'event retry leaves the selected radius intact');
    assert.deepEqual(externalRequests, [], 'UI preview must not load a map API or external AI');
    assert.deepEqual(errors, []);
    console.log('PASS screen revision: guest/home/store copy, store-centered circles, peer filtering/selection/keyboard, all 46 original events, responsive layouts, route/clock retention, event failure/retry and zero external requests.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
