'use strict';
const assert = require('node:assert/strict');
const D = require('../meeting-data.js');
const now = new Date('2026-09-12T14:00:00+09:00');
const total = (rows, key) => rows.reduce((n, r) => n + r[key], 0);
const g = D.guidance(14, now);
assert.equal(g.period.start, '2026-08-04');
assert.equal(g.period.end, '2026-09-02');
assert.equal(g.count, 30);
const rows = D.records.filter(row => row.date >= g.period.start && row.date <= g.period.end);
assert.equal(g.average, total(rows.filter(row => row.hour === 14), 'netAmount') / 30);
assert.ok(Math.abs(g.share - total(rows.filter(row => row.hour === 14), 'netAmount') / total(rows, 'netAmount') * 100) < 1e-10);
const hours = Array.from({length:12}, (_,i)=>D.guidance(i+8,now));
assert.ok(Math.abs(total(hours,'share')-100)<1e-10);
assert.ok(hours.every(row=>row.checks.length===2));
assert.notEqual(D.guidance(8,now).checks[0].title,D.guidance(18,now).checks[0].title);
assert.match(D.guidance(19,now).checks[1].title,/다음 영업일/);
assert.equal(D.guidance(2,now).average,null);
assert.equal(D.guidance(14,new Date('2026-07-15T14:00:00+09:00')).average,null);
assert.ok(!g.text.includes('7일'));
console.log('PASS rolling 30-day average, hourly sales share, two contextual actions, future peak and missing data');

const c = D.neighborhoodInsights(now);
assert.equal(c.weekdayLabel,'토요일');
assert.equal(c.count,4);
assert.equal(c.slots.length,6);
const local = D.area.filter(row=>row.date>=c.period.start && row.date<=c.period.end && new Date(row.date+'T00:00:00Z').getUTCDay()===6);
const stores = D.merchantSales.filter(row=>row.date>=c.period.start && row.date<=c.period.end && new Date(row.date+'T00:00:00Z').getUTCDay()===6);
assert.equal(c.traffic,total(local,'traffic')/4);
assert.equal(c.consumption,total(stores,'amount')/4);
assert.equal(c.merchantCount,4);
assert.equal(c.slots.reduce((best,row)=>row.traffic>best.traffic?row:best).label,'12~14시');
assert.equal(D.neighborhoodInsights(new Date('2026-09-12T15:00:00Z')).weekdayLabel,'일요일');
assert.equal(D.neighborhoodInsights(new Date('2026-06-30T14:00:00+09:00')).slots.length,0);
console.log('PASS same-weekday cohorts, six hourly aggregates, participating store scope and Seoul date rollover');

const insight = D.salesInsight(D.periods.month, now);
const analysis = D.analyze(D.periods.month);
const slot = analysis.slots.find(row => row.hour === 14);
assert.equal(insight.salesAverage, slot.sales / 31);
assert.equal(insight.storefrontAverage, slot.storefront / 31);
assert.equal(insight.share, slot.sales / analysis.sales * 100);
assert.equal(D.salesInsight(D.periods.month, new Date('2026-09-12T20:00:00+09:00')).status, 'off_hours');
assert.equal(D.salesInsight({start:'2027-01-01',end:'2027-01-31',previousStart:'2026-12-01',previousEnd:'2026-12-31'}, now).status, 'no_data');
console.log('PASS current two-hour diagnosis: observed-day averages, same-period share, missing data and off-hours');
